### ISSUE TITLE
permission .cache

### ISSUE THREAD

**Issue by cdoan1** [cdoan1/pytorch-imageclassifier#7]
```
* Serving Flask app "image_classifier" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
[2020-06-13 03:08:48,432] ERROR in app: Exception on /predict [POST]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/conda/lib/python3.7/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/flask/views.py", line 88, in view
    self = view.view_class(*class_args, **class_kwargs)
  File "/opt/image-classifier/image_classifier.py", line 18, in __init__
    self.model = models.alexnet(pretrained=True)
  File "/opt/conda/lib/python3.7/site-packages/torchvision/models/alexnet.py", line 63, in alexnet
    progress=progress)
  File "/opt/conda/lib/python3.7/site-packages/torch/hub.py", line 480, in load_state_dict_from_url
    os.makedirs(model_dir)
  File "/opt/conda/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/conda/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/conda/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/.cache'
10.131.0.10 - - [13/Jun/2020 03:08:48] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
```

**Comment by cdoan1** [comment]
* resolved with changes to the Dockerfile
